language: elixir
os:
  - linux
elixir:
  - 1.8
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - 1.2
otp_release:
  - 21.2
  - 20.3
  - 19.3
  - 18.3
env:
matrix:
  include:
    - elixir: 1.8
      otp_release: 21.2
      script:
        - MIX_ENV=cover mix coveralls.travis --trace
    - elixir: 1.8
      otp_release: 21.2
      script:
        - mix credo --all --format=oneline
    - elixir: 1.8
      otp_release: 21.2
      script:
        - mix bench
  exclude:
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 18.3
    - elixir: 1.7
      otp_release: 18.3
    - elixir: 1.6
      otp_release: 18.3
    - elixir: 1.5
      otp_release: 21.2
    - elixir: 1.4
      otp_release: 21.2
    - elixir: 1.3
      otp_release: 21.2
    - elixir: 1.3
      otp_release: 20.3
    - elixir: 1.2
      otp_release: 21.2
    - elixir: 1.2
      otp_release: 20.3
  allow_failures:
    - elixir: 1.8
      otp_release: 21.2
      script:
        - mix bench
branches:
  only:
    - master
before_install:
  - epmd -daemon
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test --trace
